In [1]:
import numpy as np

In [7]:
y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.3,0.7,1,0,0.5])

In [5]:
def mae(y_pred,y_true):
    total_cost = 0
    for yp,yt in zip(y_pred,y_true):
        total_cost += abs(yp-yt)
    print("Total Cost: ",total_cost)
    mae = total_cost/len(y_pred)
    print("Mean Absolute Error: ",mae)
    return mae

In [9]:
def mse(y_pred,y_true):
    total_cost = 0
    for yp,yt in zip(y_pred,y_true):
        total_cost += (yp-yt)**2
    print("Total Cost: ",total_cost)
    mae = total_cost/len(y_pred)
    print("Mean Squared Error: ",mae)
    return mae

In [8]:
mae(y_pred,y_true)

Total Cost:  2.5
Mean Absolute Error:  0.5


0.5

In [15]:
np.mean(np.abs(y_pred-y_true))

0.5

In [10]:
mse(y_pred,y_true)

Total Cost:  1.83
Mean Squared Error:  0.366


0.366

In [16]:
np.mean(np.square(y_true - y_pred))

0.366

In [21]:
eps = 1e-15
np.log([eps])

array([-34.53877639])

In [31]:
y_pred_new = [max(i,eps) for i in y_pred]
y_pred_new

[1, 1, 1e-15, 1e-15, 1]

In [30]:
y_pred_new = [min(i,1-eps) for i in y_pred]
y_pred_new

[0.999999999999999, 0.999999999999999, 0, 0, 0.999999999999999]

In [32]:
y_pred_new = np.array(y_pred_new)
y_pred_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [33]:
np.log(y_pred_new)

array([  0.        ,   0.        , -34.53877639, -34.53877639,
         0.        ])